// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ScriptRunner.Data;

#nullable disable

namespace ScriptRunner.WinForms.Migrations
{
    [DbContext(typeof(ContextDB))]
    partial class ContextDBModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ScriptRunner.Core.Models.ConnectionProfile", b =>
                {
                    b.Property<long>("ProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ProfileId"));

                    b.Property<string>("ConnectionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConnectionSource")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EncryptedConnectionString")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProfileId");

                    b.HasIndex("ConnectionName")
                        .IsUnique();

                    b.ToTable("TSYProfiles");
                });

            modelBuilder.Entity("ScriptRunner.Core.Models.ExceptionLog", b =>
                {
                    b.Property<long>("ExceptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ExceptionId"));

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("GeneratedDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("ExceptionId");

                    b.ToTable("TSYExceptionLogs");
                });

            modelBuilder.Entity("ScriptRunner.Core.Models.ExecutedScripts", b =>
                {
                    b.Property<long>("ScriptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ScriptId"));

                    b.Property<DateTime>("ExecutedOn")
                        .HasColumnType("datetime2");

                    b.Property<long>("ProfileId")
                        .HasColumnType("bigint");

                    b.Property<string>("ScriptText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("ScriptId");

                    b.HasIndex("ProfileId");

                    b.ToTable("TSYScripts");
                });

            modelBuilder.Entity("ScriptRunner.Core.Models.ExecutedScripts", b =>
                {
                    b.HasOne("ScriptRunner.Core.Models.ConnectionProfile", "connectionProfiles")
                        .WithMany("ExecutedScripts")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("connectionProfiles");
                });

            modelBuilder.Entity("ScriptRunner.Core.Models.ConnectionProfile", b =>
                {
                    b.Navigation("ExecutedScripts");
                });
#pragma warning restore 612, 618
        }
    }
}
